### ISSUE TITLE
Causes crash on launch with Spectrum mod, on Fabric 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [LordDeatHunter/Alloy-Forgery#71] opened 2022-09-29 16:19 UTC
[crash-2022-09-30_00.12.45-client.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/9676837/crash-2022-09-30_00.12.45-client.txt)

Mod in question: [Spectrum](https://www.curseforge.com/minecraft/mc-mods/spectrum)

**Comment by gliscowo** [comment] 2022-09-29 17:24
Duplicate of #69

**Closed by gliscowo** 2022-09-29 17:24 UTC

**Comment by TalEdd** [comment] 2022-09-30 17:05
Noted, thank you! Managed to get it running now.
