### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by NikkoYatt** [LordDeatHunter/Alloy-Forgery#67] opened 2022-09-07 08:24 UTC
[crash-2022-09-07_10.22.58-client.txt](https://github.com/LordDeatHunter/Alloy-Forgery/files/9504179/crash-2022-09-07_10.22.58-client.txt)

**Comment by gliscowo** [comment] 2022-09-11 14:20
This issue is almost certainly not caused by Alloy Forgery. According to the report you sent, the Fabric Networking API is causing the crash. This could be caused by an incompatible version of either Fabric API or some other mod which includes a newer version - it's not really possible to tell with just this information. In any case, it's highly unlikely for this to be caused by AF and as such I'll close this issue. Feel free to reopen if you discover more evidence pointing towards AF being at fault
Cheers

**Closed by gliscowo** 2022-09-11 14:20 UTC
