### ISSUE TITLE
Minecraft crashed with java.util.NoSuchElementException when initializing game

### ISSUE THREAD

**Issue by ColdTearsYY** [LordDeatHunter/Alloy-Forgery#70] opened 2022-09-28 15:07 UTC
Crash report: https://paste.ubuntu.com/p/X7kQnmTKQs/
Use Alloy forgery 2.0.16+1.19 and owo 0.8.2+1.19.

**Comment by Noaaan** [comment] 2022-09-28 16:34
Duplicate of #69

**Closed by Noaaan** 2022-09-28 16:34 UTC
