### ISSUE TITLE
Crashing when interacting with forge

### ISSUE THREAD

**Issue by nvb-uy** [LordDeatHunter/Alloy-Forgery#107] opened 2023-05-03 19:27 UTC
Only happens when right-clicking on the forge, doesn't happen when using hoppers.

Fabric 1.19.2

Latest log provided by the user that reported it:
https://pastebin.com/BVmy43Ti

**Comment by Noaaan** [comment] 2023-05-03 20:28
Duplicate of #80

**Closed as not planned by Noaaan** 2023-05-03 20:28 UTC
Labels: type: duplicate
