### ISSUE TITLE
Minecraft crash when play

### ISSUE THREAD

**Issue by OneDayGame435** [LordDeatHunter/Alloy-Forgery#92] opened 2022-12-24 15:51 UTC
[crash-2022-12-25_00.48.48-server.txt](https://github.com/wisp-forest/alloy-forgery/files/10298840/crash-2022-12-25_00.48.48-server.txt)
Pls help <3

**Comment by Noaaan** [comment] 2022-12-24 15:54
This crash explicitly mentions Gobber. Are you sure this is related to Alloy Forgery?

**Comment by BasiqueEvangelist** [comment] 2022-12-24 17:06
Are you using the latest Gobber? This is already fixed in the repo, and a release with the fix is out
https://www.curseforge.com/minecraft/mc-mods/gobber-fabric/files/4086199 should be what you need

**Comment by gliscowo** [comment] 2022-12-25 00:57
As the problem is not caused by Alloy Forgery, I'll go ahead and close this issue
Cheers

**Closed as not planned** 2022-12-25 00:57 UTC
