### ISSUE TITLE
apparently it works on 1.18.1 but hopper functionality is broken 

### ISSUE THREAD

**Issue by superdude808** [LordDeatHunter/Alloy-Forgery#29] opened 2021-12-17 13:32 UTC
works fine on 1.18.1 if you don't mind all forms of automating the forge being broken i.e. hopper interactions not working as intended 

- right side of forge controller inserts one ore and only one ore into every slot no stacking at all
- bottom of forge multi block not working with hoppers at all so no extracting outputs
- left side of forge controller only works with inputting buckets of lava via hopper 

what I'm surprised by is the fact that the code for this mod is robust enough to still function through an accidental version updating don't ask me how i updated everything by accident i'm still lost on that front myself

**Comment by glisco03** [comment] 2021-12-18 22:41
The fact that you could not extract anything was most likely caused by an incompatibility with Lithium, which is fixed in the [latest release](https://github.com/LordDeatHunter/Alloy-Forgery/releases/tag/2.0.8%2B1.18). The right hopper only inserting one ore was intended behavior but because it kept confusing people we have now changed it to stop inserting as soon as a valid recipe is present. The left hopper only inserting fuel is also intended behavior, this stays as is to make it possible to use fuel items in recipes

**Closed by glisco03** 2021-12-18 22:41 UTC

**Comment by Noaaan** [comment] 2021-12-18 22:46
For some extra clarification: there are other fuels available for the forge by default, like coal, coal blocks and blaze rods

**Comment by superdude808** [comment] 2021-12-19 04:42
sorry about the poor wording to clarify the forge was only accepting lava buckets via hopper all other fuels where left sitting in the hopper and weren't inserted into the forge at all, i could manually add the other fuels tho, i had blocks of coal sitting in the hopper and was wondering why the forge had no fuel in it before i checked the hopper and discovered they where just sitting there

second i was using version 2.0.7 of the mod at the time and am about to test version 2.0.8 

thank you for your work and for creating this mod
