### ISSUE TITLE
KubeJS Scripts Won't Load With Alloy Forgery on 1.19.2

### ISSUE THREAD

**Issue by muhammedesadcomert** [LordDeatHunter/Alloy-Forgery#102] opened 2023-03-31 11:01 UTC
Minecraft: 1.19.2
Fabric: 0.14.17
Fabric API: 0.76.0+1.19.2
KubeJS: 1902.6.0-build.142
Alloy Forgery: 2.0.19+1.19

KubeJS Script Log: https://mclo.gs/ty2Nu98#L392

**Comment by Noaaan** [comment] 2023-03-31 11:33
Duplicate of #98, the fix is already available for latest Alloy Forgery (2.0.19+1.19.4, marked as beta/pre-release)
There are currently no plans to backport it to 1.19.2.

**Closed as not planned by Noaaan** 2023-03-31 11:33 UTC
Labels: type: duplicate, type: compatibility

**Comment by muhammedesadcomert** [comment] 2023-03-31 11:59
I changed the title. So, you should pin this issue for other players facing this issue instead of closing it. This way you can avoid duplicates.
