### ISSUE TITLE
[1.18.2] [Fabric] Incompatible with megane

### ISSUE THREAD

**Issue by ConqAra** [LordDeatHunter/Alloy-Forgery#83] opened 2022-11-12 06:10 UTC
Crashes when launched with [Megane](https://github.com/badasintended/megane) mod
[CrashLog](https://paste.ee/p/1SpoF)
Similar issue referenced in megane mod developer's [github](https://github.com/badasintended/megane/issues/55)

**Comment by Noaaan** [comment] 2022-11-12 10:50
Duplicate of #82

**Closed as completed by Noaaan** 2022-11-12 10:50 UTC
Labels: type: duplicate
