### ISSUE TITLE
Crash of latest 1.18.2 version

### ISSUE THREAD

**Issue by StockiesLad** [LordDeatHunter/Alloy-Forgery#84] opened 2022-11-14 11:55 UTC
[crash-2022-11-14_22.49.10-client.txt](https://github.com/wisp-forest/alloy-forgery/files/10002684/crash-2022-11-14_22.49.10-client.txt)

**Comment by Noaaan** [comment] 2022-11-14 12:17
Duplicate of #79

**Closed as completed by Noaaan** 2022-11-14 12:17 UTC
Labels: type: duplicate, type: compatibility
