### ISSUE TITLE
1.18.2 crash

### ISSUE THREAD

**Issue by Monster-Zer0** [LordDeatHunter/Alloy-Forgery#79] opened 2022-11-08 04:07 UTC
https://aofpaste.com/awowuyijin.yaml

not sure if it is a mod conflict, but it was working for some time and then I updated to newest version causing crash.

**Comment by gliscowo** [comment] 2022-11-08 14:04
This is a known incompatibility with Incubus Core. Sadly there's nothing we can do about it, it has to be fixed on their end. They have fixed versions for 1.19, you might need to stick with older Alloy Forgery on 1.18 though
Cheers

**Closed as not planned** 2022-11-08 14:04 UTC
Labels: type: duplicate, type: compatibility

**Comment by Noaaan** [comment] 2022-11-08 15:29
This is sorta a duplicate of #69. 
A PR with a fix for Incubus Core will be released soon:tm:
